name: Build Check

on:
  pull_request:
    branches: [main, release*]

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: Cache Dependencies
        uses: c-hive/gha-yarn-cache@v1

      - name: Intall Dependencies
        run: yarn

      - name: Build check
        run: yarn build